import express from "express";
import dotenv from "dotenv";
import * as indexRouter from "./src/modules/index.router.js";
import path from "path";
import { fileURLToPath } from "url";
import connectDB from "./DB/connection.js";
const __direName = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__direName, "/config/.env") });
const baseUrl = process.env.BASEURL;
const port = process.env.PORT || 5000;
const app = express();
app.use(express.json());
app.use(`${baseUrl}/auth`, indexRouter.authRouter);
app.use(`${baseUrl}/user`, indexRouter.userRouter);
app.use(`${baseUrl}/comment`, indexRouter.commentRouter);
app.use(`${baseUrl}/post`, indexRouter.postRouter);
app.use("*", (req, res) => {
  return res.status(404).json({ message: "In-valid routing" });
});
connectDB();
app.listen(port, () => console.log(`Running................${port}`));